USE [master]
GO
/****** Object:  Database [db_envios]    Script Date: 28/9/2025 23:30:06 ******/
CREATE DATABASE [db_envios]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'db_envios', FILENAME = N'C:\SQLdata\db_envios.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'db_envios_log', FILENAME = N'C:\SQLdata\db_envios_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [db_envios] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [db_envios].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [db_envios] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [db_envios] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [db_envios] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [db_envios] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [db_envios] SET ARITHABORT OFF 
GO
ALTER DATABASE [db_envios] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [db_envios] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [db_envios] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [db_envios] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [db_envios] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [db_envios] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [db_envios] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [db_envios] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [db_envios] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [db_envios] SET  ENABLE_BROKER 
GO
ALTER DATABASE [db_envios] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [db_envios] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [db_envios] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [db_envios] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [db_envios] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [db_envios] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [db_envios] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [db_envios] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [db_envios] SET  MULTI_USER 
GO
ALTER DATABASE [db_envios] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [db_envios] SET DB_CHAINING OFF 
GO
ALTER DATABASE [db_envios] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [db_envios] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [db_envios] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [db_envios] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [db_envios] SET QUERY_STORE = ON
GO
ALTER DATABASE [db_envios] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [db_envios]
GO
/****** Object:  Table [dbo].[DetalleEnvio]    Script Date: 28/9/2025 23:30:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DetalleEnvio](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[idEnvio] [int] NOT NULL,
	[idProducto] [int] NOT NULL,
	[cantidad] [int] NOT NULL,
	[comentario] [nvarchar](200) NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Envio]    Script Date: 28/9/2025 23:30:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Envio](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[fecha] [date] NOT NULL,
	[dniCliente] [char](8) NOT NULL,
	[direccion] [nvarchar](200) NOT NULL,
	[palabraSecreta] [nvarchar](50) NOT NULL,
	[estado] [nvarchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Producto]    Script Date: 28/9/2025 23:30:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Producto](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[nombre] [nvarchar](100) NOT NULL,
	[precio] [decimal](10, 2) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DetalleEnvio]  WITH CHECK ADD  CONSTRAINT [FK_DetalleEnvio_Envio] FOREIGN KEY([idEnvio])
REFERENCES [dbo].[Envio] ([id])
GO
ALTER TABLE [dbo].[DetalleEnvio] CHECK CONSTRAINT [FK_DetalleEnvio_Envio]
GO
ALTER TABLE [dbo].[DetalleEnvio]  WITH CHECK ADD  CONSTRAINT [FK_DetalleEnvio_Producto] FOREIGN KEY([idProducto])
REFERENCES [dbo].[Producto] ([id])
GO
ALTER TABLE [dbo].[DetalleEnvio] CHECK CONSTRAINT [FK_DetalleEnvio_Producto]
GO
USE [master]
GO
ALTER DATABASE [db_envios] SET  READ_WRITE 
GO

USE [db_envios]
GO

INSERT INTO Producto(nombre, precio) VALUES
('Camiseta', 1500.00),
('Pantalón', 2500.50),
('Zapatos', 4000.75),
('Gorra', 800.00),
('Mochila', 3200.25);

INSERT INTO [dbo].[Envio] (fecha, dniCliente, direccion, palabraSecreta, estado) VALUES
('2025-09-20', '12345678', 'Calle Falsa 123', 'clave1', 'Pendiente'),
('2025-09-21', '87654321', 'Av. Siempre Viva 742', 'clave2', 'Enviado'),
('2025-09-22', '11223344', 'Calle Luna 55', 'clave3', 'Entregado'),
('2025-09-23', '44332211', 'Av. Sol 101', 'clave4', 'Pendiente'),
('2025-09-24', '55667788', 'Calle Estrella 77', 'clave5', 'Cancelado');

INSERT INTO [dbo].[DetalleEnvio] (idEnvio, idProducto, cantidad, comentario) VALUES
(1, 1, 2, 'Para regalo'),
(1, 3, 1, 'Entrega urgente'),
(2, 2, 1, NULL),
(2, 4, 3, 'Verificar talla'),
(3, 5, 1, 'Empaque delicado'),
(4, 1, 1, NULL),
(4, 5, 2, 'Revisar stock'),
(5, 3, 2, 'Enviar con factura');

