// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace proyectoPratica01.Dominio.Clases;

public partial class Articulo
{
    public int IdArticulo { get; set; }

    public string Nombre { get; set; }

    public int? PrecioU { get; set; }

    public bool Activo { get; set; }

    public virtual ICollection<DetallesFactura> DetallesFacturas { get; set; } = new List<DetallesFactura>();
}