// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace proyectoPratica01.Dominio.Clases;

public partial class DetallesFactura
{
    public int IdDetFactura { get; set; }

    public int NroFactura { get; set; }

    public int? IdArticulo { get; set; }

    public int? Cantidad { get; set; }

    public virtual Articulo IdArticuloNavigation { get; set; }

    public virtual Factura NroFacturaNavigation { get; set; }
}