// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace proyectoPratica01.Dominio.Clases;

public partial class Factura
{
    public int NroFactura { get; set; }

    public DateOnly? Fecha { get; set; }

    public int? IdFormaPago { get; set; }

    public string Cliente { get; set; }

    public bool Activo { get; set; }

    public virtual ICollection<DetallesFactura> DetallesFacturas { get; set; } = new List<DetallesFactura>();
    [JsonIgnore]
    public virtual FormasPago IdFormaPagoNavigation { get; set; }
}